config/routes.rb
Testmed::Application.routes.draw do
  devise_for :admins
  devise_for :users

  resources :trials

  resources :invitations do
    member do
    end
    collection do
      post 'create_existing'
      get 'edit_permissions'
    end
  end

  root :to => 'trials#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  #devise :database_authenticatable, :registerable,
  #       :recoverable, :rememberable, :trackable, :validatable
  # no registration for admin
  devise :database_authenticatable, :trackable, :timeoutable, :lockable, :token_authenticatable


  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :invitations

end

app/models/invitation.rb
class Invitation < ActiveRecord::Base

  require 'digest/md5'

  attr_accessible :invited_email, :trial_ids, :user_id

  scope :not_yet_registered, where(:user_id => nil)

  before_save :generate_key
  after_create :email_user
  before_destroy :notify_user_removed

  belongs_to :admin
  belongs_to :user

  has_and_belongs_to_many :trials
  accepts_nested_attributes_for :trials

  validates_presence_of :admin_id
  validate :invited_email_or_id
  validates_format_of :invited_email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, :allow_nil => true

  private

  def generate_key
    # TODO: move salt to constant later
    # only for non existing users, don't need generate it for invitation to new resources
    self.invited_key = Digest::MD5.hexdigest("salt#{self.invited_email}") if self.user_id.nil?
  end

  def email_user
    # Sending invitation for existing user for changing it's permissions
    if self.user_id
      SelfMailer.new_permissions(self).deliver
    else
      SelfMailer.invitation(self).deliver
    end
  end

  def invited_email_or_id
    if invited_email.blank? && user_id.blank?
      errors.add(:base, "Need to add user or email")
    end
  end

  def notify_user_removed
    # Send email notifying user about removed permissions
  end

end

app/models/trial.rb
class Trial < ActiveRecord::Base
  attr_accessible :title

  has_and_belongs_to_many :invitations

  validates_presence_of :title

end

app/models/user.rb
class User < ActiveRecord::Base

  require 'digest/md5'

  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :invitations
  has_many :trials, :through => :invitations

  validate :good_key, :on => :create
  after_create :tie_with_invitation

  # param can be id or Trial obj
  def can_view_trial?(trial)
    if trial.is_a?(Trial)
      obj = trial
    else
      obj = Trial.find trial
    end
    obj && self.trials.include?(obj)
  end

  private

  # NOTE: user has to register with the email he was invited with because of the code below
  # pass in additional param like "original_email" and check that if you want to be able to use different email for register
  def good_key
    invitation = Invitation.where("invited_email = ?", self.email).first
    if invitation.nil? || (invitation.invited_key != Digest::MD5.hexdigest("salt#{self.email}")) # TODO: move salt to constant
      errors.add(:invited_key, 'is wrong')
    end
  end

  def tie_with_invitation
    invitation = Invitation.where("invited_email = ?", self.email).first
    invitation.update_attribute(:user_id, self.id) if invitation
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController

  before_filter :authenticate_admin!

  def new
    @invitation = Invitation.new

    respond_to do |format|
      format.html
      format.json { render json: @invitation }
    end
  end

  def create
    emails = params[:invitation][:invited_email] ? params[:invitation][:invited_email].split(',').map(&:strip) : []
    if emails.any? && (params[:invitation][:trial_ids] && params[:invitation][:trial_ids].count == 1)
      emails.each do |email|
        invitation = Invitation.new(params[:invitation])
        invitation.invited_email = email
        invitation.admin = current_admin
        if invitation.save
          flash[:success] = "#{email} invited with key #{invitation.invited_key}"
        else
          flash[:error] = "#{email} wasn't invited"
        end
      end
    else
      flash[:error] = "Select one resource"
    end
    respond_to do |format|
      format.html { redirect_to action: "new" }
    end
  end

  def create_existing
    user_id = params[:invitation][:user_id]
    invitation = Invitation.new(params[:invitation])
    invitation.user_id = user_id
    invitation.admin = current_admin

    respond_to do |format|
      if invitation.save
        flash[:success] = "Resource assigned"
        format.html { redirect_to action: "edit_permissions", user_id: user_id  }
      else
        flash[:error] = "Couldn't assign resource"
        format.html { redirect_to action: "edit_permissions", user_id: user_id  }
      end
    end
  end

  def edit_permissions
    @invitation = Invitation.new
    @user = User.find params[:user_id]
  end

end

app/controllers/registrations_controller.rb
# DEPRECATED CLASS
class RegistrationsController < Devise::RegistrationsController

  def new
    super
  end

  def create
      build_resource(sign_up_params)
      if resource.save
        if resource.active_for_authentication?
          sign_in(resource_name, resource)
          redirect_to root_url
        else
          set_flash_message :notice, :inactive_signed_up, :reason => resource.inactive_message.to_s
          expire_session_data_after_sign_in!
          redirect_to after_inactive_sign_up_path_for(resource)
        end
      else
        clean_up_passwords(resource)
        render :new
      end

  end

end

app/controllers/trials_controller.rb
class TrialsController < ApplicationController

  before_filter :authenticate_admin!, :except => [:show, :index]
  before_filter :check_user_permissions, :only => [:show]

  # GET /trials
  # GET /trials.json
  def index
    @trials = Trial.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @trials }
    end
  end

  # GET /trials/1
  # GET /trials/1.json
  def show
    @trial = Trial.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @trial }
    end
  end

  # GET /trials/new
  # GET /trials/new.json
  def new
    @trial = Trial.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @trial }
    end
  end

  # GET /trials/1/edit
  def edit
    @trial = Trial.find(params[:id])
  end

  # POST /trials
  # POST /trials.json
  def create
    @trial = Trial.new(params[:trial])

    respond_to do |format|
      if @trial.save
        format.html { redirect_to @trial, notice: 'Trial was successfully created.' }
        format.json { render json: @trial, status: :created, location: @trial }
      else
        format.html { render action: "new" }
        format.json { render json: @trial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /trials/1
  # PUT /trials/1.json
  def update
    @trial = Trial.find(params[:id])

    respond_to do |format|
      if @trial.update_attributes(params[:trial])
        format.html { redirect_to @trial, notice: 'Trial was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @trial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trials/1
  # DELETE /trials/1.json
  def destroy
    @trial = Trial.find(params[:id])
    @trial.destroy

    respond_to do |format|
      format.html { redirect_to trials_url }
      format.json { head :no_content }
    end
  end

  private

  def check_user_permissions
    if !(admin_signed_in? || (user_signed_in? && current_user.can_view_trial?(params[:id])))
      redirect_to root_url, :notice => "You don't have access to that resource"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trials_helper.rb
module TrialsHelper
end

app/views/invitations/_existing_form.html.haml
= form_for @invitation, :url => { :action => "create_existing" }, :html => { :method => "post" } do |f|
  -if @invitation.errors.any?
    #error_explanation
      %h2= "#{pluralize(@invitation.errors.count, "error")} prohibited this trial from being saved:"
      %ul
        - @invitation.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.hidden_field :user_id, :value => @user.id
  .field
    = f.label :trial_ids, "Add to"
    - @user ? exclude = @user.trials.pluck(:id) : exclude = 0
    - Trial.where("id NOT IN (?)", exclude).all.each do |trial|
      %p
        = check_box_tag "invitation[trial_ids][]", trial.id, false
        = trial.title
  .actions
    = f.submit 'Send'

app/views/invitations/_form.html.haml
.validation_messages
= form_for @invitation do |f|
  -if @invitation.errors.any?
    #error_explanation
      %h2= "#{pluralize(@invitation.errors.count, "error")} prohibited this trial from being saved:"
      %ul
        - @invitation.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :invited_email, "User email (comma separated)"
    = f.text_area :invited_email, :rows => 5
  .field
    = f.label :trial_ids, "Resources to see"
    - Trial.all.each do |trial|
      %p
        = radio_button_tag "invitation[trial_ids][]", trial.id, false
        = trial.title
  .actions
    = f.submit 'Send'

app/views/invitations/_users.html.haml
-if User.any?
  %ul
  - User.all.each do |user|
    %li
      = link_to user.email, edit_permissions_invitations_path(:user_id => user.id)
- else
  %p No existing users, invite the first one on the left

-if Invitation.not_yet_registered.any?
  %p Invited emails
  %ul
  - Invitation.not_yet_registered.all.each do |i|
    %li
      = "#{i.invited_email} (#{i.invited_key})"

app/views/invitations/edit_permissions.html.haml
%h1
  = @user.email
= render "existing_form"
%h3 can view
%ul
- @user.trials.all.each do |trial|
  %li
    = "Trial: #{trial.title} (#{trial.id})"

app/views/invitations/new.html.haml
.row
  .col-md-6
    %h2 New invitation
    .new_invitation_form
      = render 'form'
  .col-md-6
    %h2 Edit existing permissions
    = render 'users'

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%ul.nav.nav-tabs.pull-right
  %li
  - if admin_signed_in?
    %li
      = link_to 'Logout Admin', destroy_admin_session_path, :method=>'delete'
  - else
    %li
      = link_to 'Login Admin', new_admin_session_path
  - if admin_signed_in?
    %li
      = link_to 'Send invitation', new_invitation_path

%ul.nav.nav-tabs
  %li
    = link_to "Home", root_path, :class => 'brand'
  - if user_signed_in?
    %li
      = link_to 'Logout', destroy_user_session_path, :method=>'delete'
  - else
    %li
      = link_to 'Login', new_user_session_path
  - if user_signed_in?
    %li
      = link_to 'Edit account', edit_user_registration_path
  - else
    %li
      = link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "App_Name"
    %meta{:content => content_for?(:description) ? yield(:description) : "App_Name", :name => "description"}
    = stylesheet_link_tag :application, :media => "all"
    = javascript_include_tag :application
    = csrf_meta_tags
    = yield(:head)
  %body
    %header.navbar
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer
            %p.small admin@admin.com / test1234 (before that run rake db:seed)

app/views/trials/_form.html.haml
= form_for @trial do |f|
  -if @trial.errors.any?
    #error_explanation
      %h2= "#{pluralize(@trial.errors.count, "error")} prohibited this trial from being saved:"
      %ul
        - @trial.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .actions
    = f.submit 'Save'

app/views/trials/edit.html.haml
%h1 Editing trial

= render 'form'

= link_to 'Show', @trial
\|
= link_to 'Back', trials_path

app/views/trials/index.html.haml
%h1 Listing trials

%table
  %tr
    %th Title
    %th
    %th
    %th

  - @trials.each do |trial|
    %tr
      %td= trial.title
      %td= link_to 'Show', trial
      %td= link_to 'Edit', edit_trial_path(trial)
      %td= link_to 'Destroy', trial, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Trial', new_trial_path

app/views/trials/new.html.haml
%h1 New trial

= render 'form'

= link_to 'Back', trials_path

app/views/trials/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @trial.title

= link_to 'Edit', edit_trial_path(@trial)
\|
= link_to 'Back', trials_path